# Generated by Django 2.1.7 on 2019-03-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_lists',
            name='author_link',
            field=models.URLField(default='https://github.com/kooshine'),
        ),
        migrations.AlterField(
            model_name='article_lists',
            name='image',
            field=models.ImageField(blank=True, help_text='大图833*217，小图243*207', null=True, upload_to='article/image/%y/%m', verbose_name='封面图'),
        ),
    ]
